# site name
prefixName: 飞龙
siteName: project
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://feilongproject.github.io/
description: " Write code,change world. " #主页短句
cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
mathjax: 1

notice: 网站开发中...如有小BUG请谅解
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  应用: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片个数，从零开始
bgn: 8

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/297972654, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 飞龙project的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PC端配置
social:
  github: {url: http://github.com/feilongproject, img: /img/social/github.png}
  微博: {url: http://weibo.com/feilongproject, img: /img/social/sina.png}
  网易云: {url: https://music.163.com/user?id=1374209960, img: /img/social/wangyiyun.png}
  知乎: {url: /#, img: /img/social/zhihu.png}
  email: {url: mailto:1728904631@qq.com, img: /img/social/email.svg}
  wechat: {url: , qrcode: https://feilongproject.github.io/img/donate/wechat.jpg, img: /img/social/wechat.png} #qrcode为直链，在layout/_partial/headertop中第25行

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/feilongproject, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/feilongproject, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1728904631&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

# 已修改，只能用直链，赞赏界面在layout/donate.ejs中20/67/68行，文章赞赏在layout/_widget/common-article.ejs中47/48行
donate:
  paypal: #
  alipay: #
  wechat: https://feilongproject.github.io/img/donate/WeChanQR.jpg
  wechatSQ: https://feilongproject.github.io/img/donate/WeChanSQ.jpg
  BTCQR: #

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4 ，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2331389241
  server: netease
  type: playlist
  fixed: true
  mini: false
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: nSzPJe8FXBgBS75HvaJNCvGm-gzGzoHsz
v_appKey: cak3oxVqdyQ1YSfVSXQdPMFS
